using UnityEngine;

//This is an enum that will help us identify spells/cantrips that can be used in the game itself
//This file will only handle the spell names aspect though
public enum SpellName
{
    //Cantrips first
    AcidSplash,
    BoomingBlade,
    CreateBonfire,
    EldritchBlast,
    FaerieFire,
    FireBolt,
    Guidance,
    RayOfFrost,
    SacredFlame,
    SpareTheDying,
    ThornWhip,
    TrueStrike,
    //1st Level Spells
    ArmorOfAgathys,
    Bless,
    BurningHands,
    Command,
    CureWounds,
    DivineSmite,
    FalseLife,
    FogCloud,
    GuidingBolt,
    HealingWord,
    HellishRebuke,
    InflictWounds,
    MagicMissile,
    SearingSmite,
    Shield,
    ShieldOfFaith,
    ThunderousSmite,
    ThunderWave,
    WitchBolt,
    //2nd Level Spells
    Aid,
    Blur,
    BrandingSmite,
    CloudOfDaggers,
    DragonsBreath,
    FlamingSphere,
    GustOfWind,
    HoldPerson,
    LesserRestoration,
    MagicWeapon,
    MistyStep,
    Moonbeam,
    PrayerOfHealing,
    ScorchingRay,
    ShadowBlade,
    Silence,
    SpiritualWeapon,
    //3rd Level Spells
    AuraOfVitality,
    CallLightning,
    Counterspell,
    ElementalWeapon,
    FlameArrows,
    Fireball,
    Haste,
    HypnoticPattern,
    LifeTransference,
    LightningBolt,
    MassHealingWord,
    PsionicBlast,
    Revify,
    Slow,
    SpiritGuardians,
    VampiricTouch,
    //4th Level Spells
    AuraOfLife,
    Banishment,
    Blight,
    CharmMonster,
    Divination,
    EgoWhip,
    FreedomOfMovement,
    StaggeringSmite,
    Stoneskin,
    WallOfFire,
    //5th Level Spells
    DestructiveWave,
    GreaterRestoration,
    HoldMonster,
    HolyWeapon,
    FlameStrike,
    MassCureWounds,
    SteelWindStrike,
    WallOfForce,
    WallOfStone,
    WallOfLight,
    //6th Level Spells
    ChainLightning,
    Disintegrate,
    Harm,
    Heal,
    Sunbeam,
    WallOfIce,
    //7th Level Spells
    DivineWord,
    FingerOfDeath,
    MordenkainensSword,
    PowerWordPain,
    Regenerate,
    Resurrection,
    ReverseGravity,
    Whirlwind,
    //8th Level Spells
    DominateMonster,
    Earthquake,
    PowerWordStun,
    Sunburst,
    Tsunami,
    //9th Level Spells
    BladeOfDisaster,
    Invulnerability,
    MassHeal,
    PowerWordHeal,
    PowerWordKill,
    PsychicScream,
    PrismaticWall,
    TimeStop,
    TrueResurrection,
    Wish
}
